// src/lib/ai/medTopics.extended.ts
// Ultra-detailed medical topic taxonomy for the Med Study Partner.
// Format stays compatible with your existing app: Record<System, string[]>
// Tag naming convention: "<system>:<area>-<subarea>-<specific>"
// Keep tags lowercase, hyphen-separated, and concise (≤ 5 words per segment).
// You can safely add/remove tags; the coach will still work.

export type MedSystem =
  | "heme" | "renal" | "cards" | "pulm" | "neuro" | "endo" | "gi" | "micro" | "pharm"
  | "rheum" | "id" | "derm" | "msk" | "obgyn" | "peds" | "psych" | "ophtho" | "ent"
  | "anatomy" | "physio" | "biochem" | "genetics" | "immuno" | "path" | "ethics" | "biostats" | "radiology";

export const MED_TOPICS: Record<MedSystem, string[]> = {
  heme: [
    "heme:coag-initiation-tf-vii",
    "heme:coag-intrinsic-xii-xi-ix-viii",
    "heme:coag-extrinsic-vii-pt",
    "heme:coag-common-x-v-ii-i",
    "heme:coag-thrombin-burst",
    "heme:coag-regulation-protein-c-s-at3",
    "heme:coag-fibrinolysis-tpa-plasmin",
    "heme:coag-mixing-study",
    "heme:platelet-adhesion-vwf-gp1b",
    "heme:platelet-aggregation-gp2b3a",
    "heme:platelet-release-reaction",
    "heme:thrombocytopenia-itp-tpp-hit",
    "heme:thrombocytosis-reactive-vs-myeloproliferative",
    "heme:hemophilia-a-b-c",
    "heme:vwf-disease-types",
    "heme:vitamin-k-deficiency-warfarin",
    "heme:liver-disease-coagulopathy",
    "heme:d-dimer-utility-limits",
    "heme:dvt-pe-anticoag-algorithms",
    "heme:anticoagulation-heparin-lmwh-doac-warfarin",
    "heme:reversal-protamine-vitk-pcc",
    "heme:transfusion-prbc-ffp-plt-cryoprecip",
    "heme:transfusion-reactions-acute-delayed",
    "heme:hemolysis-intravascular-vs-extravascular",
    "heme:g6pd-oxidative-hemolysis",
    "heme:sickle-cell-crises-acute-chest",
    "heme:thalassemia-alpha-beta-traits",
    "heme:microcytic-iron-aoCD-thal-sidero",
    "heme:macrocytic-b12-folate-mds",
    "heme:normocytic-hemolytic-vs-nonhemolytic",
    "heme:leukemias-all-aml-cll-cml",
    "heme:lymphomas-hodgkin-nonhodgkin",
    "heme:myeloproliferative-pv-et-pmf-cml",
    "heme:apl-t15-17-atra",
    "heme:coombs-tests-direct-indirect",
    "heme:hb-electrophoresis-interpret",
    "heme:retic-count-index",
    "heme:hemoglobinopathies-hbe-hbc",
    "heme:iron-studies-ferritin-tsat-tibc",
    "heme:hypereosinophilia-ddx",
  ],

  renal: [
    "renal:acid-base-metabolic-acidosis-hag",
    "renal:acid-base-metabolic-acidosis-nag",
    "renal:acid-base-metabolic-alkalosis",
    "renal:acid-base-respiratory-acidosis",
    "renal:acid-base-respiratory-alkalosis",
    "renal:anion-gap-calc-delta-delta",
    "renal:winters-formula",
    "renal:rta-types-1-2-4",
    "renal:electrolytes-na-dysnatremias",
    "renal:electrolytes-k-hyper-hypo",
    "renal:electrolytes-ca-mg-phos",
    "renal:hyponatremia-hypo-euvo-hypervolemic",
    "renal:hypernatremia-euvo-hypo-hypervolemic",
    "renal:aki-prerenal-intrinsic-postrenal",
    "renal:ckd-staging-complications",
    "renal:gn-nephritic-syndromes",
    "renal:nephrotic-syndromes",
    "renal:glomerular-vs-tubulointerstitial",
    "renal:ua-casts-protein-blood",
    "renal:stone-types-ca-ox-uric-cystine-struvite",
    "renal:pyelo-vs-cystitis",
    "renal:polycystic-kidney-adhpkd-arpkd",
    "renal:diuretics-loop-thiazide-k-sparing-ca-inhib",
    "renal:acid-base-approach-stepwise",
    "renal:renal-osteodystrophy",
    "renal:dkd-algorithm-ace-arb-sglt2",
    "renal:hemodialysis-peritoneal-basics",
  ],

  cards: [
    "cards:acs-unstable-angina-nstemi-stemi",
    "cards:acs-initial-management-mona-bash",
    "cards:ekg-stemi-criteria-territories",
    "cards:mi-complications-vsd-mr-shock",
    "cards:heart-failure-hfref-hfpef",
    "cards:heart-failure-therapies-ace-arnI-bb-mra-sglt2",
    "cards:arrhythmias-af-rate-rhythm-anticoag",
    "cards:arrhythmias-vt-vf-torsades",
    "cards:brady-av-blocks",
    "cards:valves-as-ar-ms-mr",
    "cards:infective-endocarditis-duke-criteria",
    "cards:pericarditis-tamponade-constriction",
    "cards:hypertension-primary-secondary",
    "cards:hypertensive-emergency-urgency",
    "cards:lipids-statins-ascvd-risk",
    "cards:cardiomyopathies-hcm-dcm-rcm",
    "cards:shock-types-hypovolemic-cardiogenic-distributive-obstructive",
    "cards:cardiac-imaging-echo-stress-ct-ctca",
    "cards:antiplatelet-dual-therapy",
    "cards:anticoag-in-af-vte",
    "cards:post-mi-secondary-prevention",
    "cards:syncope-approach-orthostatics",
    "cards:congenital-heart-diseases-basic",
  ],

  pulm: [
    "pulm:asthma-severity-step-therapy",
    "pulm:copd-gold-groups-treatment",
    "pulm:pna-typical-atypical-cap-hap-vap",
    "pulm:pe-wells-genesia-cta-vq",
    "pulm:ards-criteria-management",
    "pulm:pleural-effusion-transudate-exudate-lights",
    "pulm:pneumothorax-primary-secondary-tension",
    "pulm:tb-screening-treatment",
    "pulm:interstitial-lung-diseases",
    "pulm:sarcoidosis",
    "pulm:lung-cancer-types-staging",
    "pulm:abg-interpretation",
    "pulm:vent-settings-peep-tv-rr-fio2",
    "pulm:oxygen-delivery-devices",
    "pulm:sleep-apnea-osa-csa",
    "pulm:aspiration-chemical-pna",
  ],

  neuro: [
    "neuro:stroke-ischemic-hemorrhagic-tt-pa-window",
    "neuro:stroke-secondary-prevention",
    "neuro:tia-vs-minor-stroke",
    "neuro:seizures-focal-generalized-status",
    "neuro:antiepileptics-spectrum-sidefx",
    "neuro:meningitis-encephalitis-algorithm",
    "neuro:movement-disorders-pd-hd-dystonia",
    "neuro:ms-diagnosis-dmts",
    "neuro:neuropathy-peripheral-gbs-cidp",
    "neuro:myasthenia-gravis-crisis",
    "neuro:headache-migraine-tension-cluster",
    "neuro:neuroanatomy-tracts-lesions",
    "neuro:brain-tumors-adult-peds",
    "neuro:spinal-cord-syndromes",
    "neuro:neuroimaging-ct-mri-cta-mra",
  ],

  endo: [
    "endo:dm-type1-type2-screening",
    "endo:dm-dka-hhs-initial-steps",
    "endo:insulin-regimens-basal-bolus",
    "endo:thyroid-hyper-hypo-graves-hashimoto",
    "endo:thyroid-nodules-cancer",
    "endo:adrenal-addisons-cushings-phaeo",
    "endo:calcium-parathyroid-hypo-hyper",
    "endo:pituitary-adenomas-prolactinoma-acro",
    "endo:lipids-endo-causes",
    "endo:osteoporosis-osteopenia-therapy",
    "endo:siadh-diabetes-insipidus",
  ],

  gi: [
    "gi:gi-bleed-upper-lower-algorithm",
    "gi:liver-failure-acute-chronic",
    "gi:cirrhosis-complications-varices-ascites-he",
    "gi:viral-hepatitis-screening-treatment",
    "gi:nafld-nash",
    "gi:pancreatitis-acute-chronic",
    "gi:ibd-uc-crohn-diagnosis-therapy",
    "gi:ibs-criteria-therapy",
    "gi:celiac-disease-serologies-biopsy",
    "gi:gerd-barretts-esophagitis",
    "gi:peptic-ulcer-hpylori",
    "gi:colorectal-cancer-screening",
    "gi:diverticulitis-diverticulosis",
    "gi:biliary-cholelithiasis-cholecystitis-choledocholithiasis",
    "gi:sbp-diagnosis-treatment",
    "gi:hepatocellular-carcinoma-surveillance",
  ],

  micro: [
    "micro:gram-positive-cocci-staph-strep-enterococcus",
    "micro:gram-positive-rods-bacillus-clostridium-listeria",
    "micro:gram-negative-rods-enterobacteriaceae",
    "micro:gram-negative-cocci-neisseria",
    "micro:anaerobes-bacteroides-prevotella",
    "micro:atypicals-mycoplasma-chlamydia-legionella",
    "micro:mycobacteria-tb-ntm",
    "micro:spirochetes-syphilis-lyme-lepto",
    "micro:rickettsial-ehrlichia-anaplasma",
    "micro:zoonoses-pasteurella-brucella",
    "micro:viruses-rna-dna-families",
    "micro:respiratory-viruses-flu-rsv-covid",
    "micro:hepatitis-viruses-a-e-b-c-d",
    "micro:hiv-basics-art-oi-prophylaxis",
    "micro:fungi-yeasts-molds-dimorphic",
    "micro:endemic-mycoses-histo-blasto-cocci",
    "micro:parasites-gi-blood-tissue",
    "micro:stewardship-empiric-narrowing",
    "micro:sterilization-disinfection",
  ],

  pharm: [
    "pharm:autonomics-sympathomimetics-lytics",
    "pharm:cholinergics-anticholinergics",
    "pharm:cardio-antihypertensives",
    "pharm:cardio-antianginals-antiplatelets",
    "pharm:antiarrhythmics-class-i-iv",
    "pharm:heart-failure-therapies",
    "pharm:anticoagulants-heparin-doac-warfarin",
    "pharm:antimicrobials-beta-lactams",
    "pharm:antimicrobials-macrolides-quinolones-tetracyclines",
    "pharm:antifungals-azoles-echinocandins-amphoB",
    "pharm:antivirals-hiv-hep-herpes",
    "pharm:endocrine-insulins-thyroid-steroids",
    "pharm:neuro-antiepileptics-antipsychotics",
    "pharm:analgesics-nsaids-opioids",
    "pharm:gi-ppis-h2-antiemetics",
    "pharm:onc-chemo-targeted-io-basics",
    "pharm:adverse-effects-monitoring",
    "pharm:pk-pd-therapeutic-window",
  ],

  rheum: [
    "rheum:ra-dx-tx-dmards",
    "rheum:lupus-criteria-flare",
    "rheum:sero-negative-spondyloarthropathies",
    "rheum:gout-pseudogout-crystals",
    "rheum:vasculitis-anca-giant-cell-takayasu",
    "rheum:sjogrens-scleroderma-mctd",
    "rheum:myositis-dermato-poly",
  ],

  id: [
    "id:sepsis-bundles-source-control",
    "id:fever-of-unknown-origin",
    "id:osteomyelitis",
    "id:cellulitis-abscess",
    "id:endocarditis",
    "id:catheter-associated-infections",
    "id:sti-syphilis-gc-ct-hsv",
    "id:prophylaxis-prepost-exposure",
    "id:travel-medicine-vaccines",
  ],

  derm: [
    "derm:eczema-psoriasis-sebderm",
    "derm:acne-rosacea-hidradenitis",
    "derm:urticaria-angioedema",
    "derm:drug-eruptions-stevens-johnson-ten",
    "derm:bacterial-skin-impetigo-erysipelas",
    "derm:fungal-dermatophytes-candida",
    "derm:viral-hsv-varicella-zoster",
    "derm:skin-cancers-bcc-scc-melanoma",
    "derm:vasculitic-rashes-palpable-purpura",
    "derm:bullous-pemphigus-bullous-pemphigoid",
  ],

  msk: [
    "msk:fracture-types-initial-management",
    "msk:shoulder-dislocation-rotator-cuff",
    "msk:knee-meniscus-ligaments",
    "msk:hip-fracture-arthroplasty",
    "msk:spine-red-flags-cauda-equina",
    "msk:osteomyelitis-septic-arthritis",
    "msk:low-back-pain-approach",
    "msk:osteoporosis-prevention-treatment",
  ],

  obgyn: [
    "obgyn:prenatal-care-screening",
    "obgyn:normal-labor-stages",
    "obgyn:hypertensive-disorders-pregnancy",
    "obgyn:gestational-diabetes",
    "obgyn:ectopic-pregnancy",
    "obgyn:postpartum-hemorrhage",
    "obgyn:contraception",
    "obgyn:abnormal-uterine-bleeding",
    "obgyn:gynecologic-oncology",
    "obgyn:stds-pregnancy-considerations",
  ],

  peds: [
    "peds:well-child-care-immunizations",
    "peds:febrile-infant-algorithm",
    "peds:bronchiolitis-croup-epiglottitis",
    "peds:asthma-peds",
    "peds:congenital-heart-lesions-basics",
    "peds:failure-to-thrive",
    "peds:neonatal-jaundice",
    "peds:peds-rashes-scarlet-roseola-measles",
    "peds:developmental-milestones",
  ],

  psych: [
    "psych:depression-bipolar",
    "psych:anxiety-ocd-ptsd",
    "psych:psychosis-schizophrenia",
    "psych:substance-use-disorders",
    "psych:eating-disorders",
    "psych:personality-disorders-overview",
    "psych:suicide-risk-assessment",
    "psych:psychopharm-ssri-snri-tca-maoi",
  ],

  ophtho: [
    "ophtho:acute-angle-closure-glaucoma",
    "ophtho:open-angle-glaucoma",
    "ophtho:retinal-detachment",
    "ophtho:central-retinal-artery-vein-occlusion",
    "ophtho:diabetic-retinopathy",
    "ophtho:macular-degeneration",
    "ophtho:conjunctivitis-keratitis",
  ],

  ent: [
    "ent:otitis-media-externa",
    "ent:sinusitis-rhinitis",
    "ent:pharyngitis-tonsillitis",
    "ent:epistaxis-management",
    "ent:head-and-neck-cancer",
    "ent:airway-emergencies",
  ],

  anatomy: [
    "anatomy:upper-limb-nerves-arteries",
    "anatomy:lower-limb-nerves-arteries",
    "anatomy:thorax-mediastinum-coronary",
    "anatomy:abdomen-peritoneum-portal",
    "anatomy:pelvis-perineum",
    "anatomy:neuroanatomy-cortex-tracts-cn",
  ],

  physio: [
    "physio:cardiac-cycle-preload-afterload",
    "physio:renal-handling-na-k-h2o",
    "physio:resp-mechanics-vq-shunt-deadspace",
    "physio:endocrine-axes-feedback",
    "physio:gi-motility-secretion-absorption",
  ],

  biochem: [
    "biochem:metabolism-glycolysis-tca-etc",
    "biochem:gluconeogenesis-glycogen",
    "biochem:lipid-metabolism",
    "biochem:urea-cycle",
    "biochem:vitamins-cofactors-deficiencies",
  ],

  genetics: [
    "genetics:inheritance-ad-ar-x-linked",
    "genetics:trinucleotide-repeats",
    "genetics:chromosomal-disorders",
    "genetics:mendelian-vs-complex",
    "genetics:genetic-testing-counseling",
  ],

  immuno: [
    "immuno:innate-vs-adaptive",
    "immuno:humoral-cell-mediated",
    "immuno:hypersensitivity-types-1-4",
    "immuno:immunodeficiencies",
    "immuno:autoimmunity-mechanisms",
    "immuno:vaccines-response",
  ],

  path: [
    "path:inflammation-acute-chronic",
    "path:cell-injury-necrosis-apoptosis",
    "path:neoplasia-hallmarks",
    "path:hemodynamics-edema-thrombosis-embolism",
    "path:amyloidosis",
  ],

  ethics: [
    "ethics:consent-capacity",
    "ethics:confidentiality-duty-to-warn",
    "ethics:end-of-life-dnr-dni",
    "ethics:research-ethics",
    "ethics:cultural-competence-bias",
  ],

  biostats: [
    "biostats:sensitivity-specificity-ppv-npv",
    "biostats:likelihood-ratios",
    "biostats:bayes-theorem",
    "biostats:study-designs-rct-cohort-casecontrol",
    "biostats:bias-confounding-effect-modification",
    "biostats:survival-analysis",
    "biostats:noninferiority-equivalence",
  ],

  radiology: [
    "radiology:chest-xray-interpretation",
    "radiology:us-ct-mri-indications",
    "radiology:contrast-risks",
    "radiology:trauma-fast-ectopic-us",
    "radiology:neuroimaging-stroke-head-ct",
  ],
};

// Flatten helper (optional): returns array of "system:topic" strings across all systems.
export const ALL_MED_TAGS: string[] = Object.values(MED_TOPICS).flat();

// Utility to get topics by prefix (system or area)
export function findTags(prefix: string): string[] {
  const p = prefix.toLowerCase();
  return ALL_MED_TAGS.filter(t => t.startsWith(p));
}
